/* Signed-in Home: Home canvas, Keep Exploring intro, then wheel/Scroll reveal. */
function initHomeCanvas() {
  const canvas=document.getElementById('homeCanvas'), cardsHost=document.getElementById('exploreCards'), connectors=document.getElementById('exploreConnectors'), next=document.getElementById('homeCanvasNext'), previous=document.getElementById('homeCanvasPrev'), explorePanel=document.getElementById('keep-exploring'), scrollButton=document.getElementById('exploreScroll');
  if(!canvas||!cardsHost||!connectors||!next||!previous||!explorePanel||!scrollButton)return;
  const items=[
    {category:'CPG Updates',title:'CPG AI Hub: new practical tools and workflows',source:'CPG Vietnam',date:'31 Jul 2026',image:'assets/images/cpg-international.png',href:'insights.html#quick-learns'},
    {category:'CPG Updates',title:'Responsible AI and data safety',source:'CPG AI Hub',date:'30 Jul 2026',image:'assets/images/microsoft-copilot.svg',href:'learn.html#what-is-ai'},
    {category:'CPG Updates',title:'Share a workplace AI opportunity',source:'CPG Vietnam',date:'29 Jul 2026',image:'assets/images/cpg-international.png',href:'submit-idea.html#share-ideas'},
    {category:'LinkedIn',title:'Digital transformation updates from CPG Vietnam',source:'CPG International Vietnam',date:'29 Jul 2026',image:'assets/images/cpg-international.png',href:'https://vn.linkedin.com/company/cpg-international-vietnam',external:true},
    {category:'LinkedIn',title:'CPG Vietnam project updates',source:'CPG Vietnam',date:'28 Jul 2026',image:'assets/images/sketchup.png',href:'https://cpgvietnam.com.vn/',external:true},
    {category:'LinkedIn',title:'Explore global AI design practices',source:'CPG AI Hub',date:'27 Jul 2026',image:'assets/images/revit.png',href:'insights.html#global-firms'},
    {category:'Research Papers',title:'What early AI adopters are learning about work',source:'Anthropic Research',date:'25 Jul 2026',image:'assets/images/claude.png',href:'https://www.anthropic.com/research/how-ai-is-transforming-work-at-anthropic',external:true},
    {category:'Research Papers',title:'AI value in design and engineering',source:'Autodesk Research',date:'24 Jul 2026',image:'assets/images/autodesk-ai.jpg',href:'https://www.autodesk.com/design-make/articles/2026-ai-pulse',external:true},
    {category:'Research Papers',title:'AI foundations for non-technical staff',source:'CPG Learning',date:'23 Jul 2026',image:'assets/images/chatgpt.png',href:'learn.html#what-is-ai'},
    {category:'AI Industry News',title:'How AI is changing the way teams work',source:'Microsoft WorkLab',date:'22 Jul 2026',image:'assets/images/microsoft-copilot.svg',href:'https://news.microsoft.com/annual-work-trend-index-2026/',external:true},
    {category:'AI Industry News',title:'AI trends shaping everyday work',source:'CPG AI Hub',date:'21 Jul 2026',image:'assets/images/gemini.jpg',href:'insights.html#aios'},
    {category:'AI Industry News',title:'Global firms using AI in practice',source:'CPG AI Hub',date:'20 Jul 2026',image:'assets/images/kling.jpg',href:'insights.html#global-firms'},
    {category:'Tools & Tutorials',title:'Approved AI tools at CPG',source:'CPG AI Hub',date:'19 Jul 2026',image:'assets/images/excel.webp',href:'tools.html#ai-tools'},
    {category:'Tools & Tutorials',title:'Find a tool by work task',source:'CPG AI Hub',date:'18 Jul 2026',image:'assets/images/autocad.png',href:'tools.html#task-help'},
    {category:'Tools & Tutorials',title:'Design and visualisation workflow',source:'CPG AI Hub',date:'18 Jul 2026',image:'assets/images/veras.jpg',href:'tools.html#design-workflow'},
    {category:'Events & Training',title:'Quick AI learning videos',source:'CPG Learning',date:'17 Jul 2026',image:'assets/images/d5.png',href:'learn.html#quick-learns'},
    {category:'Events & Training',title:'Events and practical training',source:'CPG Learning',date:'16 Jul 2026',image:'assets/images/midjourney.webp',href:'insights.html#quick-learns'},
    {category:'Events & Training',title:'Submit the next CPG AI use case',source:'CPG Vietnam',date:'15 Jul 2026',image:'assets/images/cpg-international.png',href:'submit-idea.html#share-ideas'}
  ];  cardsHost.innerHTML=items.map((item,index)=>`<a class="explore-card" href="${item.href}"${item.external?' target="_blank" rel="noopener"':''} style="--delay:${100+index*55}ms"><span class="explore-thumb"><img src="${item.image}" alt="" loading="lazy"></span><span><span class="explore-card-category">${item.category}</span><h3>${item.title}</h3><span class="explore-card-meta">${item.source} · ${item.date}</span></span></a>`).join('');
  const drawConnectors=()=>{if(!document.body.classList.contains('explore-expanded')||innerWidth<=640)return;const cards=[...cardsHost.querySelectorAll('.explore-card')],panelRect=explorePanel.getBoundingClientRect();if(cards.length<6)return;const centers=cards.map(card=>{const rect=card.getBoundingClientRect();return{x:rect.left-panelRect.left+rect.width/2,y:rect.top-panelRect.top+rect.height/2}}),pairs=[[0,1],[2,1],[3,4],[5,4],[6,7],[8,7],[9,10],[11,10],[12,13],[14,13],[15,16],[17,16],[1,4],[1,7],[4,10],[7,13],[10,16],[13,16]];connectors.setAttribute('viewBox',`0 0 ${panelRect.width} ${panelRect.height}`);connectors.innerHTML=pairs.map(([a,b])=>`<line x1="${centers[a].x}" y1="${centers[a].y}" x2="${centers[b].x}" y2="${centers[b].y}"></line>`).join('')};
  const setExploreStage=expanded=>{const canvasTop=canvas.getBoundingClientRect().top+scrollY,active=expanded&&document.body.classList.contains('canvas-exploring');document.body.classList.toggle('explore-expanded',active);canvas.dataset.stage=active?'items':'intro';scrollButton.setAttribute('aria-hidden',active?'true':'false');scrollButton.tabIndex=active?-1:0;cardsHost.querySelectorAll('.explore-card').forEach(card=>card.tabIndex=active?0:-1);if(active)setTimeout(drawConnectors,340);else connectors.innerHTML='';requestAnimationFrame(()=>scrollTo({top:canvasTop,left:0,behavior:'auto'}));setTimeout(()=>scrollTo({top:canvasTop,left:0,behavior:'auto'}),80)};
  const setCanvas=destination=>{const exploring=destination==='explore'&&document.body.classList.contains('demo-authenticated');document.body.classList.toggle('canvas-exploring',exploring);canvas.dataset.canvas=exploring?'explore':'home';next.setAttribute('aria-hidden',exploring?'true':'false');next.tabIndex=exploring?-1:0;previous.setAttribute('aria-hidden',exploring?'false':'true');previous.tabIndex=exploring?0:-1;setExploreStage(false);setTimeout(()=>{(exploring?scrollButton:next).focus({preventScroll:true})},850)};
  next.addEventListener('click',()=>setCanvas('explore'));previous.addEventListener('click',()=>setCanvas('home'));scrollButton.addEventListener('click',()=>setExploreStage(true));
  let wheelLocked=false;explorePanel.addEventListener('wheel',event=>{if(!document.body.classList.contains('canvas-exploring')||Math.abs(event.deltaY)<10||wheelLocked)return;const expanded=document.body.classList.contains('explore-expanded');if((event.deltaY>0&&!expanded)||(event.deltaY<0&&expanded)){event.preventDefault();setExploreStage(event.deltaY>0);wheelLocked=true;setTimeout(()=>wheelLocked=false,900)}},{passive:false});
  document.addEventListener('keydown',event=>{if(!document.body.classList.contains('demo-authenticated')||event.altKey||event.ctrlKey||event.metaKey||event.target.matches('input,textarea,select,[contenteditable="true"]'))return;if(event.key==='ArrowRight'&&canvas.dataset.canvas!=='explore')setCanvas('explore');if(event.key==='ArrowLeft'&&canvas.dataset.canvas==='explore')setCanvas('home');if((event.key==='ArrowDown'||event.key==='PageDown')&&canvas.dataset.canvas==='explore'){event.preventDefault();setExploreStage(true)}if((event.key==='ArrowUp'||event.key==='PageUp')&&canvas.dataset.canvas==='explore'&&document.body.classList.contains('explore-expanded')){event.preventDefault();setExploreStage(false)}});
  addEventListener('resize',()=>requestAnimationFrame(drawConnectors),{passive:true});new MutationObserver(()=>{if(!document.body.classList.contains('demo-authenticated')&&canvas.dataset.canvas==='explore')setCanvas('home')}).observe(document.body,{attributes:true,attributeFilter:['class']});setCanvas('home');
}
Object.assign(VI_TRANSLATIONS,{'Keep Exploring':'Tiếp tục khám phá','Keep':'Tiếp tục','Exploring':'Khám phá','Scroll':'Cuộn','Click an item to explore':'Nhấp vào một mục để khám phá','View all News →':'Xem tất cả Tin tức →','CPG Updates':'Cập nhật CPG','Research Papers':'Nghiên cứu','AI Industry News':'Tin tức ngành AI','Tools & Tutorials':'Công cụ & Hướng dẫn','Events & Training':'Sự kiện & Đào tạo','CPG AI Hub: new practical tools and workflows':'CPG AI Hub: công cụ và quy trình thực tế mới','Digital transformation updates from CPG Vietnam':'Cập nhật chuyển đổi số từ CPG Việt Nam','What early AI adopters are learning about work':'Những bài học ban đầu về AI trong công việc','How AI is changing the way teams work':'AI đang thay đổi cách các nhóm làm việc như thế nào','Choose an approved AI tool for your task':'Chọn công cụ AI được phê duyệt cho công việc','Build a clear AI-assisted design workflow':'Xây dựng quy trình thiết kế có AI hỗ trợ rõ ràng','CPG Vietnam':'CPG Việt Nam','CPG Learning':'Đào tạo CPG'});
Object.assign(VI_TRANSLATIONS,{
 'Responsible AI and data safety':'AI có trách nhiệm và an toàn dữ liệu','Share a workplace AI opportunity':'Chia sẻ một cơ hội AI tại nơi làm việc','CPG Vietnam project updates':'Cập nhật dự án CPG Việt Nam','Explore global AI design practices':'Khám phá thực hành thiết kế AI toàn cầu','AI value in design and engineering':'Giá trị AI trong thiết kế và kỹ thuật','AI foundations for non-technical staff':'Nền tảng AI cho nhân sự không chuyên kỹ thuật','AI trends shaping everyday work':'Xu hướng AI định hình công việc hằng ngày','Global firms using AI in practice':'Các công ty toàn cầu ứng dụng AI trong thực tế','Approved AI tools at CPG':'Công cụ AI được phê duyệt tại CPG','Find a tool by work task':'Tìm công cụ theo công việc','Design and visualisation workflow':'Quy trình thiết kế và trực quan hóa','Quick AI learning videos':'Video học AI nhanh','Events and practical training':'Sự kiện và đào tạo thực hành','Submit the next CPG AI use case':'Gửi trường hợp ứng dụng AI tiếp theo của CPG'
});
